### ISSUE TITLE
Elasticsearch won't start when using M1 Mac

### ISSUE THREAD

**Issue by glennjacobs** [lando/elasticsearch#12]

**Comment by glennjacobs** [comment]
Sorry, not sure if this should have been submitted on the `lando/lando` repo or here?

**Comment by glennjacobs** [comment]
If it's of any help, the following custom service works for me on my M1 mac.

```
services:
  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:7.10
      command: /elastic-entrypoint.sh elasticsearch
      ports:
        - "9200:9200"
proxy:
  elasticsearch:
    - elasticsearch-project.lndo.site:9200
```
