### ISSUE TITLE
elasticsearch version 8 is not supported

### ISSUE THREAD

**Issue by stloc** [lando/elasticsearch#15]
```
...
services:
  myelastic:
    type: elasticsearch:8
    portforward: true
  patch:
    type: elasticsearch:8.2.3
...
```
```
$ lando rebuild
ERROR ==> elasticsearch version 8 is not supported
```
