### ISSUE TITLE
Error: unknown shorthand flag: 'T' in -T

### ISSUE THREAD

**Issue by roberttolton** [lando/elasticsearch#39]
Host: Apple M2 Max
OS: Ventura 13.6.7

`.lando.yml` contains:

```
name: ecommerce-api
keys:
  - id_rsa
services:
  database:
    type: mysql:8.0
    portforward: 8500
    creds:
      user: vendure
      password: vendure
      database: database
    authentication: mysql_native_password
  elasticsearch:
    type: elasticsearch:8
    portforward: true

```

Upon trying to rebuild my project I get the error:

```
[+] Healthchecking 2/2
 ✔ Healthcheck ecommerceapi_database_1       Passed
 ✖ unknown shorthand flag: 'T' in -T                  FAILED
[+] Running 1/1
 ✔ Container ecommerceapi_elasticsearch_1  Started                                                                                                                                                                                     0.3s
[+] Killing 1/1
 ✔ Container ecommerceapi_elasticsearch_1  Killed
```

```
  ⚠ The service "elasticsearch" failed its healthcheck
    Failed with unknown shorthand flag: 'T' in -T
    This may be ok but we recommend you run the command below to investigate:
    Run lando logs -s elasticsearch
```

The logs show:

```
elasticsearch_1  | [2024-10-11T03:24:26,267][ERROR][o.e.b.Elasticsearch      ] [lando] fatal exception while booting Elasticsearch org.elasticsearch.ElasticsearchException: Failed to bind service
```

Not sure why it failed to bind the service, I have nothing running on the `9200` port on my host Mac:

```
sudo lsof -n -i :9200 | grep LISTEN
(nothing)
```
