### ISSUE TITLE
Kibana container built but crashes after start

### ISSUE THREAD

**Issue by Niyabi** [lando/elasticsearch#6]
Hi, I wanted to add Kibana to my Magento 2 local env but always after start container crashes. Tried different cofigurations, google'ing but nothing made it work. 

My landofile:
```yml
name: magento-lando
recipe: lemp
config:
  webroot: docroot/pub
  php: '7.4'
  database: mariadb:10.4
  xdebug: 'false'
  composer_version: '2.0.7'
  config:
    php: config/php.ini
    vhosts: config/nginx.conf

proxy:
  appserver_nginx:
    - magento2.lndo.site
  mailhog:
    - mailhog.lndo.site
  phpmyadmin:
    - pma.lndo.site
  kibana:
    - kibana.lndo.site:5601

services:
  appserver:
    type: php:7.4
    build_as_root:
      - apt update -y -q && apt install -y libxslt-dev libsodium-dev cron curl wget
      - docker-php-ext-install xsl sockets sodium
    build:      
    run_as_root:
      - service cron start
    run:
    xdebug: true
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"

  database:
    # You can connect externally via "external_connection" info from `lando info`.
    portforward: true
    creds:
      # These credentials are used only for this specific instance.
      # You can use the same credentials for each Lando site.
      user: magento
      password: magento
      database: magento

  phpmyadmin:
    type: phpmyadmin
    portforward: true
    hosts:
      - database

  elasticsearch:
    type: elasticsearch:7.10.2
    portforward: 9200
    mem: 1025m
    overrides:
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  
  kibana:
    type: compose
    services:
      user: root
      image: bitnami/kibana:7.10.2
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
    overrides:
      environment:
        KIBANA_ELASTICSEARCH_URL: "elasticsearch"
        KIBANA_ELASTICSEARCH_PORT_NUMBER: 9200
        KIBANA_HOST: kibana.lndo.site
        KIBANA_PORT_NUMBER: 5601
  
  redis:
    type: redis
    persist: false
    portforward: 6379

  mailhog:
    type: mailhog
    portforward: 1025
    hogfrom:
      - appserver

  node:
    type: node:14
    ssl: false
    globals:
      grunt-cli: latest
```

Error:
```
Starting magentolando_kibana_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-core/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
```

**Comment by labboy0276** [comment]
@Niyabi what version of lando are you on?

**Comment by Niyabi** [comment]
> @Niyabi what version of lando are you on?

I'm using 3.6.0, windows + wsl ubuntu

**Comment by anthropos9** [comment]
Using v3.6.5 this worked for me:
```
services:
  elasticsearch:
    type: elasticsearch:7.10.2
    portforward: 9200
    mem: 1025m
    overrides:
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    type: compose
    services:
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      image: bitnami/kibana:7.10.2
      command: '/opt/bitnami/scripts/kibana/entrypoint.sh /opt/bitnami/scripts/kibana/run.sh'

proxy:
  kibana:
    - kibana.lndo.site:5601
```
@Niyabi  the overrides you had in the original were preventing it from running correctly - at least in my case.
